spring:
  application:
    name: processor-service
  main:
    banner-mode: off

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: always
      group:
        liveness:
          include:
            - livenessState
        readiness:
          include:
            - readinessState
  endpoints:
    web:
      exposure:
        include: prometheus, health
  prometheus:
    metrics:
      export:
        enabled: true
  health:
    redis:
      enabled: false
    livenessState:
      enabled: true
    readinessState:
      enabled: true